// src/enums/AssessmentType.ts
export enum AssessmentType {
  FILL_BLANK = "FILL_BLANK",
  VOCAB_CONTEXT = "VOCAB_CONTEXT",
  SENTENCE_ORDER = "SENTENCE_ORDER",
  READING_SHORT = "READING_SHORT",
  READING_DIALOGUE = "READING_DIALOGUE",
  READING_LETTER = "READING_LETTER",
  READING_PERSONAL = "READING_PERSONAL",
  READING_PLACE = "READING_PLACE",
  READING_INFO = "READING_INFO",
  KANJI_READING = "KANJI_READING",
  KANJI_MEMORY = "KANJI_MEMORY",
}
