export enum AssessmentType {
  // ===== KANJI =====
  KANJI_READING = "KANJI_READING",
  KANJI_MEMORY = "KANJI_MEMORY",

  // ===== VOCAB =====
  VOCAB_CONTEXT = "VOCAB_CONTEXT",

  // ===== GRAMMAR =====
  FILL_BLANK = "FILL_BLANK",
  SENTENCE_ORDER = "SENTENCE_ORDER",
  PARAPHRASE = "PARAPHRASE",
  GRAMMAR_SELECT = "GRAMMAR_SELECT",
  TEXT_COMPLETION = "TEXT_COMPLETION",

  // ===== READING =====
  READING_SHORT = "READING_SHORT",
  READING_DIALOGUE = "READING_DIALOGUE",
  READING_LETTER = "READING_LETTER",
  READING_PERSONAL = "READING_PERSONAL",
  READING_PLACE = "READING_PLACE",
  READING_INFO = "READING_INFO",
  READING_MEDIUM = "READING_MEDIUM",

  // ===== LISTENING =====
  LISTENING_TASK = "LISTENING_TASK",
  LISTENING_CHOICE_PREVIEW = "LISTENING_CHOICE_PREVIEW",
  LISTENING_MAIN_IDEA = "LISTENING_MAIN_IDEA",
  LISTENING_RESPONSE = "LISTENING_RESPONSE",
  LISTENING_INSTANT = "LISTENING_INSTANT",
  LISTENING_LONG = "LISTENING_LONG",
}